import { VOCABULARY_STORAGE_KEY, emptyVocabulary } from './vocabulary-store.js';

const STATUS = [['new','待学习'],['reviewing','复习中'],['mastered','已掌握']];
const [{ printVocabularyIds }, stored] = await Promise.all([chrome.storage.session.get(['printVocabularyIds']), chrome.storage.local.get([VOCABULARY_STORAGE_KEY])]);
const state = stored[VOCABULARY_STORAGE_KEY] ?? emptyVocabulary();
const selected = new Set(printVocabularyIds ?? state.entries.map((entry)=>entry.id));
const entries = state.entries.filter((entry)=>selected.has(entry.id));
document.querySelector('#generated-date').textContent = `生成于 ${new Intl.DateTimeFormat('zh-CN',{dateStyle:'long'}).format(new Date())} · 共 ${entries.length} 个词条`;
document.querySelector('#cover-stats').replaceChildren(...STATUS.map(([value,label])=>stat(entries.filter((entry)=>entry.status===value).length,label)));
const groups=document.querySelector('#groups');
for(const [status,label] of STATUS){const items=entries.filter((entry)=>entry.status===status).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(!items.length)continue;const section=document.createElement('section');section.className='word-group';const header=document.createElement('div');header.className='group-header';const heading=document.createElement('h2');heading.textContent=label;const count=document.createElement('span');count.textContent=`${items.length} 个词条`;header.append(heading,count);section.append(header,...items.map(wordCard));groups.append(section);}
document.querySelector('#print-button').addEventListener('click',()=>window.print());

function wordCard(entry){const article=document.createElement('article');article.className='word-card';const title=document.createElement('div');title.className='word-title';const h3=document.createElement('h3');h3.textContent=entry.enrichment?.headword||entry.original_term;const meta=document.createElement('p');meta.textContent=[entry.enrichment?.ipa,entry.enrichment?.part_of_speech].filter(Boolean).join(' · ');title.append(h3,meta);if(entry.enrichment_status!=='ready'){const pending=document.createElement('span');pending.className='pending';pending.textContent='释义待补充';title.append(pending);}const meaning=document.createElement('div');meaning.className='meaning';const h4=document.createElement('h4');h4.textContent=entry.enrichment?.contextual_meaning_zh||'待补充语境释义';const definition=document.createElement('p');definition.textContent=entry.enrichment?.simple_definition_en||'';const usage=document.createElement('p');usage.className='usage';usage.textContent=entry.enrichment?.usage_note||'';const sentence=document.createElement('blockquote');sentence.className='sentence';sentence.textContent=entry.sentence;meaning.append(h4,definition,usage,sentence);if(entry.note){const note=document.createElement('p');note.className='note';note.textContent=`我的 Note：${entry.note}`;meaning.append(note);}const source=document.createElement('p');source.className='source';const first=entry.sources?.[0];source.textContent=[first?.source_label,first?.question_number?`第 ${first.question_number} 题`:'',new Intl.DateTimeFormat('zh-CN').format(new Date(entry.created_at))].filter(Boolean).join(' · ');meaning.append(source);article.append(title,meaning);return article;}
function stat(value,label){const node=document.createElement('div');const strong=document.createElement('strong');strong.textContent=value;const span=document.createElement('span');span.textContent=label;node.append(strong,span);return node;}
